In [ ]:
#variable
a = '10'
print("I am ",a,"years old")

I am  10 years old


In [ ]:
#adding two int variables
a=int(input("enter a value:"))
b=int(input("enter b value:"))
print("sum of two numbers is ",a+b)
print("difference is ",a-b)
print("product is ",a*b)
print("coefficient is ",a/b)
print("remainder is ",a%b)
print("power of a to b ",a**b)
print("floor division is ",a//b6)

enter a value:3
enter b value:6
sum of two numbers is  9
difference is  -3
product is  18
coefficient is  0.5
remainder is  3
power of a to b  729
floor division is  0


In [ ]:
#take salary from the user if the salary is more than 50000 there is 10% tax print his final salary
a=int(input("enter salary :"))
if a>=50000:
  print("your salary after tax is ",a-(a*(10/100)))
else:
  print("your salary less than 50000 no tax initiated.")

enter salary :753951
your salary after tax is  678555.9


In [ ]:
#get the salary from the user if the salary is more than or equal to 50k apply 10% tax deduction if the salary is less than 50k apply 5% tax if the salary if more than 70k apply 12% tax if salary exists 1Lk print your'e promoted to next level
n=int(input("enter salary:"))
if n>=100000:
  print("you are promoted to next level.")
elif n>70000:
  print("your salary after 12% tax:",n-(n*(0.12)))
elif n>=50000:
  print("your salary after 10%  tax:",n-(n*(0.1)))
else:
  print("your salary after 5% tax:",n-(n*(0.05)))

enter salary:80000
your salary after 12% tax: 70400.0


In [ ]:
#for loop:
a=int(input("Enter a value: "))
for i in range(1,11):
  print(a,'x',i,'=',a*i)

Enter a value: 11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110


In [ ]:
#while loop
a=int(input("enter the number :"))
i=1
while(i<=10):
  print(a,'x',i,'=',a*i)
  i=i+1

enter the number :11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110


In [ ]:
#list heterogenous
l1=[1,"kill",89,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
89
chat
hello
hello
insert
9.1
True
append


In [ ]:
#mutable
l1.append("append") #add elements in back of the list
print(l1)

[1, 'kill', 89, 'chat', 9.1, True, 'append']


In [ ]:
#inserting elements into list
l1.insert(4,"hello")
print(l1)

[1, 'kill', 'hello', 'insert', 'hello', 9.1, True, 'append', 3]


In [ ]:
#list extend or adding two lists
l2=[1,2,3]
l1.extend(l2)
print(l1)

[1, 'kill', 89, 'chat', 'hello', 'hello', 'insert', 9.1, True, 'append', 1, 2, 3, 1, 2, 3]


In [ ]:
#deleting an element in list
l1.remove('kill')
print(l1)

[1, 'insert', 9.1, True, 'append', 3]


In [ ]:
#deleting using pop
l1.pop(0)
print(l1)

[True, 'append', 3]


In [ ]:
#clear the list
l1.clear() #clear the list
print(l1)

[]


In [ ]:
#Create a list of ten integer elements print their squares save these squares in a new list
a=[1,2,3,4,5,6,7,8,9,10]
b=[i**2 for i in a] #list comprehension
print(b)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comprehension
#new list=[output for if]
a=[23,58,69,47,15,62]
b=[i*i for i in a if i>50]
print(b)

[3364, 4761, 3844]


In [ ]:
#lc
#new list=[(statement of if) if (condition) else (statement of else) for]
l=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in l]
print(res)


['X', 4489, 'X', 'X', 4761]


In [ ]:
#take the salary from the user if salary<50000->10% tax other wise 15% tax
list=[78000,50400,34000,23000,14000]
s=[  n-(n*0.1)   if   n<50000   else     n-(n*0.15)  for n in list  ]
  #    st if     if     cond    else      st else        for
print(s)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Dictionary
#dict_name={key:value, key:value.....}


In [ ]:
#creat dictonary
dict={"principal":"venkat",'vice principal':"sai","dean":"sawith","Hod":"rakesh"}
print(dict)


{'principal': 'venkat', 'vice principal': 'sai', 'dean': 'sawith', 'Hod': 'rakesh'}


In [ ]:
dict3={"dept":"cse","Details":{"year":2,"sec":"D","count":14}}
print("year is",dict3["Details"][year])
print("Section is",dict3["details"][sec])
print("count is",dict3["details"][count])

NameError: name 'year' is not defined

In [ ]:
idl=[1,2,3,4,5]
name=["sai",'venkat','ravi','ravi','siva']
new_zip=(zip(idl,name))
for i in new_zip:
  print(i)

(1, 'sai')
(2, 'venkat')
(3, 'ravi')
(4, 'ravi')
(5, 'siva')


In [ ]:
#NUMPY
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
import numpy as np
A1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #elements in each columns
print(A1)
print(A1.ndim)
print(A1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
#three dimension
import numpy as np
A2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A2)
print(A2.ndim)
print(A2.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [ ]:
A2=np.ones((5,6))
print(A2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
A=np.zeros((5,6))
print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
A=np.eye(5,6)
print(A)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [ ]:
A=np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all numbers that are divisible by 8 using a range function b/w 1 and 1000
A = np.arange(8,1000,8)
print(A)

[  8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136 144
 152 160 168 176 184 192 200 208 216 224 232 240 248 256 264 272 280 288
 296 304 312 320 328 336 344 352 360 368 376 384 392 400 408 416 424 432
 440 448 456 464 472 480 488 496 504 512 520 528 536 544 552 560 568 576
 584 592 600 608 616 624 632 640 648 656 664 672 680 688 696 704 712 720
 728 736 744 752 760 768 776 784 792 800 808 816 824 832 840 848 856 864
 872 880 888 896 904 912 920 928 936 944 952 960 968 976 984 992]


In [ ]:
#linspace
A=np.linspace(4,50,8)  #splitting a range of numbers into numbers having common differences
print(A)

[ 4.         10.57142857 17.14285714 23.71428571 30.28571429 36.85714286
 43.42857143 50.        ]


tuple and sets
Document upto today
qr code

In [ ]:
#sets
s={'s',1,'r',2,True}
print(s)
tuple and sets
Document upto today
qr code
#type
print(type(s))
#update
s.update("i")
print(s)
#remove
s.remove('i')
print(s)
#pop
s.pop()
print(s)
#clear
s.clear()
print(s)

{1, 2, 's', 'r'}
4
<class 'set'>
{'i', 1, 2, 'r', 's'}
{1, 2, 'r', 's'}
{2, 'r', 's'}
set()


In [ ]:
#set operations
s1={1,2,3,4,5}
s2={4,5,6,7,8}
#union
print(s1.union(s2))
#intersection
print(s1.intersection(s2))
#difference
print(s1.difference(s2))
#symmetric_difference
print(s1.symmetric_difference(s2))
#subset
print(s1.issubset(s2))
#superset
print(s1.issuperset(s2))
#disjoint
print(s1.isdisjoint(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
False
False
False


In [ ]:
#tuples
t=(1,2,3,4,5)
print(t)
#concat
t1=(1,2,3)+(4,5,6,3)
print(t1)
#lenght
print(len(t))
#repetition
t2=("hi! ")*4
print(t2)


(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5, 6, 3)
5
hi! hi! hi! hi! 


In [ ]:
#in
print(3 in t1)
#index
print(t[0])
print(t[0:4])
#updating tuple using list
tl=list(t)
tl[1]=55
t=tuple(tl)
print(t)


True
1
(1, 2, 3, 4)
(1, 55, 3, 4, 5)


In [ ]:
#type
print(type(t))
#count
print(t.count(5))
#index
print(t.index(5))

<class 'tuple'>
1
4
