In [ ]:
import numpy as np
A=np.arange(1,13).reshape(4,3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
A=np.linspace(3,6,25).reshape(5,5)
print(A)

[[3.    3.125 3.25  3.375 3.5  ]
 [3.625 3.75  3.875 4.    4.125]
 [4.25  4.375 4.5   4.625 4.75 ]
 [4.875 5.    5.125 5.25  5.375]
 [5.5   5.625 5.75  5.875 6.   ]]


In [ ]:
A=np.array([58,48,62,97,36,15,28,39,46,65]).reshape(5,2)
print(A)

[[58 48]
 [62 97]
 [36 15]
 [28 39]
 [46 65]]


In [ ]:
#resize
B=np.array([89,23,45,25,656,256,65,35])  #changes the shape of original array
B.resize(2,2,2)
print(B)

[[[ 89  23]
  [ 45  25]]

 [[656 256]
  [ 65  35]]]


In [ ]:
A=np.array([54,95,75,35,85])
B=np.array([9,8,7,4,5])
C=(A-B)
print(C)


[45 87 68 31 80]


In [ ]:
import numpy as np
A=np.array([54,95,75,35]).reshape(2,2)
B=np.array([9,8,7,4]).reshape(2,2)
C=(A-B)
print(A)
print(B)
print("___________________________________")
print(A-B)

[[54 95]
 [75 35]]
[[9 8]
 [7 4]]
___________________________________
[[45 87]
 [68 31]]


In [ ]:
import numpy as np
A=np.array([54,95,75,35]).reshape(2,2)
B=np.array([9,8,7,4]).reshape(2,2)
C=(A*B)
print(A)
print("_______________________________")
print(B)
print("___________________________________")
print(A*B)

[[54 95]
 [75 35]]
_______________________________
[[9 8]
 [7 4]]
___________________________________
[[486 760]
 [525 140]]


In [ ]:
 import numpy as np
A=np.array([54,95,75,35]).reshape(2,2)
B=np.array([9,8,7,4]).reshape(2,2)
C=A.dot(B)#matrix
print(A)
print("_______________________________")
print(B)
print("___________________________________")
print(A*B)

[[54 95]
 [75 35]]
_______________________________
[[9 8]
 [7 4]]
___________________________________
[[486 760]
 [525 140]]


In [ ]:
A=np.array([54,97,5,62,48])
print(A.max())
print(B.min())

97
4


In [ ]:
a=np.array([5,85,56,16,475,46]).reshape(3,2)
b=np.array([4,65,5,45,1,64]).reshape(2,3)
print(a)
print("_______________________________")
print(b)
print("__________________________________")
print(a.max(axis=0))
print(a.max(axis=1))

[[  5  85]
 [ 56  16]
 [475  46]]
_______________________________
[[ 4 65  5]
 [45  1 64]]
__________________________________
[475  85]
[ 85  56 475]


In [ ]:
a=np.array([5,85,56,16,475,46]).reshape(3,2)
print(a)
print("---------------------------------")
print(a.max(axis=0))
print("--------------------------------")
print(a.max(axis=1))

[[  5  85]
 [ 56  16]
 [475  46]]
---------------------------------
[475  85]
--------------------------------
[ 85  56 475]


In [ ]:
a=np.array([35,62,48,91]).reshape(2,2)
b=np.array([64,97,29,38]).reshape(2,2)
print(a)
print("--------------------")
print(b)
print("---------------------------------")
print("after vertically stacking the arrays")
print(np.vstack((a,b)))

[[35 62]
 [48 91]]
--------------------
[[64 97]
 [29 38]]
---------------------------------
after vertically stacking the arrays
[[35 62]
 [48 91]
 [64 97]
 [29 38]]


In [ ]:
a=np.array([35,62,48,91]).reshape(2,2)
b=np.array([64,97,29,38]).reshape(2,2)
print(a)
print("--------------------")
print(b)
print("---------------------------------")
print("after horizontally stacking the arrays")
print(np.hstack((a,b)))

[[35 62]
 [48 91]]
--------------------
[[64 97]
 [29 38]]
---------------------------------
after horizontally stacking the arrays
[[35 62 64 97]
 [48 91 29 38]]


In [ ]:
a=np.array([35,62,48,91]).reshape(2,2)
b=np.array([64,97,29,38]).reshape(2,2)
print(a)
print("--------------------")
print(b)
print("---------------------------------")
print("after diagonal stacking the arrays")
print(np.dstack((a,b)))

[[35 62]
 [48 91]]
--------------------
[[64 97]
 [29 38]]
---------------------------------
after diagonal stacking the arrays
[[[35 64]
  [62 97]]

 [[48 29]
  [91 38]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after dstack")
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after stack")
print(np.stack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after stack
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
print(np.vsplit(a,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
print(np.hsplit(a,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
print(np.vsplit(a,3))

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.vsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.vsplit(a,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.hsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
a=np.arange(1,19).reshape(3,6)
print(a)
print(a.argmax(axis=0))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[2 2 2 2 2 2]


In [ ]:
a=np.array([17,4,8,56,12,33,89,21,64,55,11,13]).reshape(3,4)
print(a)
print(a.argmax(axis=0))

[[17  4  8 56]
 [12 33 89 21]
 [64 55 11 13]]
[2 2 1 0]


In [ ]:
a=np.array([17,4,8,56,12,33,89,21,64,55,11,13]).reshape(3,4)
print(a)
print(a.argmin(axis=0))

[[17  4  8 56]
 [12 33 89 21]
 [64 55 11 13]]
[1 0 0 2]


In [ ]:
a=np.array([12,34,25,66,71,88])
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Variance: ",np.var(a))
print("Standard deviatiov: ",np.std(a))

Mean:  49.333333333333336
Median:  50.0
Variance:  743.888888888889
Standard deviatiov:  27.274326552435515


TRIGNOMETRY

In [ ]:
import numpy as np
a=np.pi
print()

3.141592653589793


In [ ]:
np.rad2deg(a)

180.0

In [ ]:
b=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(b)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(b))

[ 45.  60.  90. 180.]


In [ ]:
c=np.array([0,30,45,60,90,120,180])
d=np.deg2rad(c)
print(d)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(d)

array([0.00000000e+00, 5.00000000e-01, 7.07106781e-01, 8.66025404e-01,
       1.00000000e+00, 8.66025404e-01, 1.22464680e-16])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
print(np.arctan(c))
print(np.arccos(c))
print(np.arctan(1))

[0.         1.53747533 1.54857776 1.5541312  1.55968567 1.56246319
 1.56524083]
[1.57079633        nan        nan        nan        nan        nan
        nan]
0.7853981633974483


<ipython-input-85-00150abab5e6>:2: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(c))


In [3]:
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))
print(np.arctan(c))
print(np.arcsin(c))
print(np.arccos(c))

NameError: name 'np' is not defined

In [6]:
#searching
import numpy as np
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))
print(np.where(A==90))
print(np.where(A>25))

(array([0, 4, 5]),)
(array([0, 5]),)
(array([0, 2, 4, 5]),)


In [10]:
#read an array with one dimension
import numpy as np
A=np.array([1,2,3,4])
print(n.searchsorted(A,4))

3


Linear Algebra

In [12]:
A=np.array([98,87,76,65,54,43,32,21])
B=np.array([12,23,34,45,56,67,78,89])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))

[110 110 110 110 110 110 110 110]
[ 86  64  42  20  -2 -24 -46 -68]
[8.16666667 3.7826087  2.23529412 1.44444444 0.96428571 0.64179104
 0.41025641 0.23595506]
[ 2 18  8 20 54 43 32 21]


In [13]:
A=np.array([6,8,4,2,7])
print(n.sort(A))

[2 4 6 7 8]


In [16]:
A=n.array([9,8,7,6,5])
B=n.array([4,3,2,1,9,8,5,7])
print(n.union1d(A,B))
print(n.setdiff1d(A,B))
print(n.intersect1d(A,B))

[1 2 3 4 5 6 7 8 9]
[6]
[5 7 8 9]


In [19]:
A=n.array([6,24,60,12,18])
B=n.array([6,4,10,5,4])
print(n.union1d(A,B))
print(n.setdiff1d(A,B))
print(n.intersect1d(A,B))

[ 4  5  6 10 12 18 24 60]
[12 18 24 60]
[6]


In [18]:
import numpy as np
print(np.around(3.16626,4))
print(np.trunc([-3.1666,3.6666]))
print(np.fix([-3.1666,3.6666]))
print(np.floor([-3.1666,3.6666]))
print(np.ceil([-3.1666,3.1]))

3.1663
[-3.  3.]
[-3.  3.]
[-4.  3.]
[-3.  4.]


In [21]:
A = np.array([100,200,300,400,500,600m])
print(np.cumsum(A)) #cummulative sum of array in order

[ 100  300  600 1000 1500 2100]


In [23]:
A = np.array([9,8,7,4,5,6,3,2,1])
print(np.cumprod(A))  #cummulative product of array in order

[     9     72    504   2016  10080  60480 181440 362880 362880]


In [26]:
print(np.lcm(86,95)) #lcm of two numbers
print(np.gcd(60,95)) #gcd of two numbers

8170
5


In [28]:
Ar = np.array([85,75,95])
print(np.lcm.reduce(Ar))

24225


In [29]:
Ar = np.array([14,65,87])
print(np.gcd.reduce(Ar))

1


In [30]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
from numpy import random as rd
A = rd.rand() #rand(n) #default limit 0 to 0.99 for rand function
print(A)

0.4117717474615583


A = rd.randint(50,size=(2,3))
print(A)

In [40]:
A = rd.rand()
print(A)

0.5994949692909968


In [ ]:
#there are 5 sublects psychology,nanology,medicine,onchology,anthropology
#two students have applied to do masters any of these 5 fields with a line plot show in which field theu can exel the cutoff for each subject is 70
#now student 1=[67,45,73,71,57]
#student 2=[43,67,68,53,85]
from matplot import